# $<Schema>$ https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
name: "Scan Virus - Specify NPM Packages"
on:
  workflow_dispatch:
    inputs:
      targets:
        description: "{string[]} Targets."
        required: true
jobs:
  parse-inputs:
    name: "(Parse Inputs)"
    runs-on: "ubuntu-latest"
    steps:
      - run: |
          [string]$OriginalPreference_ErrorAction = $ErrorActionPreference
          $ErrorActionPreference = 'Stop'
          [string[]]$NPMPackagesRaw = '${{github.event.inputs.targets}}' -split ";|\r?\n"
          [string[]]$NPMPackages = $NPMPackagesRaw | ForEach-Object -Process {
            return $_.Trim()
          } | Where-Object -FilterScript {
            return ($_.Length -gt 0)
          }
          [string[]]$NPMPackagesURL = @()
          foreach ($NPMPackage in $NPMPackages) {
            try {
              ((Invoke-WebRequest -Method Get -Uri "https://registry.npmjs.org/$NPMPackage" -UseBasicParsing).Content | ConvertFrom-Json -Depth 100).versions.PSObject.Properties | ForEach-Object -Process {
                $NPMPackagesURL += $_.Value.dist.tarball
              }
            } catch {
              Write-Warning -Message "NPM package ``$NPMPackage``` not found!`n$($_.Exception.Message)"
              continue
            }
          }
          if ($NPMPackagesURL.Count -gt 0) {
            Write-Host -Object "::set-output name=targets::$($NPMPackagesURL -join ";")"
          } else {
            throw 'No URL resolved!'
          }
          $ErrorActionPreference = $OriginalPreference_ErrorAction
        id: "parser"
        shell: "pwsh"
    outputs:
      targets: "${{steps.parser.outputs.targets}}"
  scan-virus-specify-npm-packages:
    name: "Scan Virus - Specify NPM Packages"
    runs-on: "ubuntu-latest"
    needs:
      - "parse-inputs"
    steps:
      - name: "Scan NPM Packages"
        uses: "hugoalh/scan-virus-ghaction@main"
        with:
          targets: "${{needs.parse-inputs.outputs.targets}}"
