# $<Schema>$ https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
name: "Scan Virus (Build)"
on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"
    types:
      - "opened"
      - "edited"
      - "reopened"
      - "synchronize"
  workflow_dispatch:
    inputs:
      deep:
        description: "{boolean} Scan deeper."
        required: false
        default: "true"
jobs:
  parse-inputs:
    name: "(Parse Inputs)"
    runs-on: "ubuntu-latest"
    steps:
      - run: |
          [string]$Deep = '${{github.event.inputs.deep}}'
          if ($Deep.Length -eq 0) {
            $Deep = 'false'
          }
          Write-Host -Object "::set-output name=deep::$Deep"
        id: "parser"
        shell: "pwsh"
    outputs:
      deep: "${{steps.parser.outputs.deep}}"
  scan-virus:
    name: "Scan Virus"
    runs-on: "ubuntu-latest"
    needs:
      - "parse-inputs"
    steps:
      - name: "Checkout Repository"
        uses: "actions/checkout@v3.0.0"
        with:
          fetch-depth: 0
      - name: "Scan Repository"
        uses: "hugoalh/scan-virus-ghaction/use-docker-build@main"
        with:
          deep: "${{needs.parse-inputs.outputs.deep}}"
          yara_enable: "true"
          experiment_yara_rulesfilter_list: "fpu.yara"
          experiment_yara_rulesfilter_mode: "include"
          experiment_yara_warning: "true"
